class Post {
  int? userId;
  int? id;
  String? title;
  String? body;

  Post.fromJson(Map<dynamic, dynamic> json) {
    userId = json["userId"];
    id = json["id"];
    title = json["title"];
    body = json["body"] +
        "asdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fdasdfasfas asdfasd asdfasdf asdfasdfasdf asdasd asdfasd fasdfasdf asdfasdf asdf asdf asdfasd asd fd";
  }
}
